In [4]:
from langchain_community.document_loaders import TextLoader #used to convert raw text into a format suitable for langchain
from langchain_text_splitters import CharacterTextSplitter # split the document into meaningfull chuncks (descriptions)
from langchain_openai import OpenAIEmbeddings #converting the chunks into embedding, call openai api
from langchain_chroma import Chroma # store in vector database (open_source)
from marshmallow import missing
# from zmq.green import device

In [5]:
from dotenv import load_dotenv

load_dotenv()

True

In [6]:
# API call requires having an account in openAI, so we can charge
# How to get the API key for OpenAI
# How to add credit on OpenAI
# How to get the API key for Hugging face

In [6]:
import pandas as pd

books = pd.read_csv("book_cleaned.csv")
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,titles_and_subtitles,tagged_description
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine..."
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,Mistaken Identity,9788172235222 On A Train Journey Home To North...
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,Journey to the East,9788173031014 This book tells the tale of a ma...
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...

In [7]:
# text_loader doesn't deal with pandas for this purpose we are going to create a text file
books["tagged_description"].to_csv("tagged_description.txt",
                                   sep="\n",
                                   index=False,
                                   header=False)

In [8]:
raw_documents = TextLoader("tagged_description.txt").load()
text_splitter = CharacterTextSplitter(chunk_size=0, chunk_overlap=0, separator='\n') # when chunk size set to 0 we make sure that priority of splitting on seperator
documents = text_splitter.split_documents(raw_documents)

Created a chunk of size 1168, which is longer than the specified 0
Created a chunk of size 1214, which is longer than the specified 0
Created a chunk of size 373, which is longer than the specified 0
Created a chunk of size 309, which is longer than the specified 0
Created a chunk of size 483, which is longer than the specified 0
Created a chunk of size 482, which is longer than the specified 0
Created a chunk of size 960, which is longer than the specified 0
Created a chunk of size 188, which is longer than the specified 0
Created a chunk of size 843, which is longer than the specified 0
Created a chunk of size 296, which is longer than the specified 0
Created a chunk of size 197, which is longer than the specified 0
Created a chunk of size 881, which is longer than the specified 0
Created a chunk of size 1088, which is longer than the specified 0
Created a chunk of size 1189, which is longer than the specified 0
Created a chunk of size 304, which is longer than the specified 0
Created a chunk of size 270, which is longer than the specified 0
Created a chunk of size 211, which is longer than the specified 0
Created a chunk of size 214, which is longer than the specified 0
Created a chunk of size 513, which is longer than the specified 0
Created a chunk of size 752, which is longer than the specified 0
Created a chunk of size 388, which is longer than the specified 0
Created a chunk of size 263, which is longer than the specified 0
Created a chunk of size 253, which is longer than the specified 0
Created a chunk of size 306, which is longer than the specified 0
Created a chunk of size 728, which is longer than the specified 0
Created a chunk of size 721, which is longer than the specified 0
Created a chunk of size 256, which is longer than the specified 0
Created a chunk of size 473, which is longer than the specified 0
Created a chunk of size 270, which is longer than the specified 0
Created a chunk of size 1267, which is longer than the specified 0
Created a chunk of size 681, which is longer than the specified 0
Created a chunk of size 243, which is longer than the specified 0
Created a chunk of size 553, which is longer than the specified 0
Created a chunk of size 521, which is longer than the specified 0
Created a chunk of size 280, which is longer than the specified 0
Created a chunk of size 787, which is longer than the specified 0
Created a chunk of size 564, which is longer than the specified 0
Created a chunk of size 523, which is longer than the specified 0
Created a chunk of size 177, which is longer than the specified 0
Created a chunk of size 297, which is longer than the specified 0
Created a chunk of size 533, which is longer than the specified 0
Created a chunk of size 559, which is longer than the specified 0
Created a chunk of size 563, which is longer than the specified 0
Created a chunk of size 385, which is longer than the specified 0
Created a chunk of size 410, which is longer than the specified 0
Created a chunk of size 461, which is longer than the specified 0
Created a chunk of size 595, which is longer than the specified 0
Created a chunk of size 476, which is longer than the specified 0
Created a chunk of size 459, which is longer than the specified 0
Created a chunk of size 257, which is longer than the specified 0
Created a chunk of size 304, which is longer than the specified 0
Created a chunk of size 614, which is longer than the specified 0
Created a chunk of size 419, which is longer than the specified 0
Created a chunk of size 887, which is longer than the specified 0
Created a chunk of size 693, which is longer than the specified 0
Created a chunk of size 302, which is longer than the specified 0
Created a chunk of size 217, which is longer than the specified 0
Created a chunk of size 277, which is longer than the specified 0
Created a chunk of size 2010, which is longer than the specified 0
Created a chunk of size 173, which is longer than the specified 0
Created a chunk of size 479, which is longer than the specified 0
Created a chunk of size 300, which is longer than the specified 0
Created a chunk of size 520, which is longer than the specified 0
Created a chunk of size 647, which is longer than the specified 0
Created a chunk of size 778, which is longer than the specified 0
Created a chunk of size 165, which is longer than the specified 0
Created a chunk of size 686, which is longer than the specified 0
Created a chunk of size 548, which is longer than the specified 0
Created a chunk of size 1225, which is longer than the specified 0
Created a chunk of size 406, which is longer than the specified 0
Created a chunk of size 1184, which is longer than the specified 0
Created a chunk of size 1214, which is longer than the specified 0
Created a chunk of size 1191, which is longer than the specified 0
Created a chunk of size 1057, which is longer than the specified 0
Created a chunk of size 244, which is longer than the specified 0
Created a chunk of size 688, which is longer than the specified 0
Created a chunk of size 876, which is longer than the specified 0
Created a chunk of size 284, which is longer than the specified 0
Created a chunk of size 766, which is longer than the specified 0
Created a chunk of size 389, which is longer than the specified 0
Created a chunk of size 417, which is longer than the specified 0
Created a chunk of size 208, which is longer than the specified 0
Created a chunk of size 209, which is longer than the specified 0
Created a chunk of size 723, which is longer than the specified 0
Created a chunk of size 209, which is longer than the specified 0
Created a chunk of size 163, which is longer than the specified 0
Created a chunk of size 526, which is longer than the specified 0
Created a chunk of size 521, which is longer than the specified 0
Created a chunk of size 214, which is longer than the specified 0
Created a chunk of size 338, which is longer than the specified 0
Created a chunk of size 899, which is longer than the specified 0
Created a chunk of size 1270, which is longer than the specified 0
Created a chunk of size 558, which is longer than the specified 0
Created a chunk of size 1635, which is longer than the specified 0
Created a chunk of size 436, which is longer than the specified 0
Created a chunk of size 249, which is longer than the specified 0
Created a chunk of size 777, which is longer than the specified 0
Created a chunk of size 716, which is longer than the specified 0
Created a chunk of size 514, which is longer than the specified 0
Created a chunk of size 958, which is longer than the specified 0
Created a chunk of size 198, which is longer than the specified 0
Created a chunk of size 1132, which is longer than the specified 0
Created a chunk of size 168, which is longer than the specified 0
Created a chunk of size 1325, which is longer than the specified 0
Created a chunk of size 851, which is longer than the specified 0
Created a chunk of size 272, which is longer than the specified 0
Created a chunk of size 801, which is longer than the specified 0
Created a chunk of size 1119, which is longer than the specified 0
Created a chunk of size 836, which is longer than the specified 0
Created a chunk of size 260, which is longer than the specified 0
Created a chunk of size 235, which is longer than the specified 0
Created a chunk of size 732, which is longer than the specified 0
Created a chunk of size 1195, which is longer than the specified 0
Created a chunk of size 710, which is longer than the specified 0
Created a chunk of size 773, which is longer than the specified 0
Created a chunk of size 278, which is longer than the specified 0
Created a chunk of size 307, which is longer than the specified 0
Created a chunk of size 356, which is longer than the specified 0
Created a chunk of size 766, which is longer than the specified 0
Created a chunk of size 767, which is longer than the specified 0
Created a chunk of size 716, which is longer than the specified 0
Created a chunk of size 2012, which is longer than the specified 0
Created a chunk of size 308, which is longer than the specified 0
Created a chunk of size 1286, which is longer than the specified 0
Created a chunk of size 1231, which is longer than the specified 0
Created a chunk of size 729, which is longer than the specified 0
Created a chunk of size 750, which is longer than the specified 0
Created a chunk of size 445, which is longer than the specified 0
Created a chunk of size 1242, which is longer than the specified 0
Created a chunk of size 309, which is longer than the specified 0
Created a chunk of size 912, which is longer than the specified 0
Created a chunk of size 304, which is longer than the specified 0
Created a chunk of size 844, which is longer than the specified 0
Created a chunk of size 1126, which is longer than the specified 0
Created a chunk of size 1073, which is longer than the specified 0
Created a chunk of size 1318, which is longer than the specified 0
Created a chunk of size 361, which is longer than the specified 0
Created a chunk of size 2834, which is longer than the specified 0
Created a chunk of size 237, which is longer than the specified 0
Created a chunk of size 240, which is longer than the specified 0
Created a chunk of size 171, which is longer than the specified 0
Created a chunk of size 204, which is longer than the specified 0
Created a chunk of size 570, which is longer than the specified 0
Created a chunk of size 206, which is longer than the specified 0
Created a chunk of size 367, which is longer than the specified 0
Created a chunk of size 1141, which is longer than the specified 0
Created a chunk of size 1004, which is longer than the specified 0
Created a chunk of size 715, which is longer than the specified 0
Created a chunk of size 710, which is longer than the specified 0
Created a chunk of size 2510, which is longer than the specified 0
Created a chunk of size 954, which is longer than the specified 0
Created a chunk of size 307, which is longer than the specified 0
Created a chunk of size 351, which is longer than the specified 0
Created a chunk of size 639, which is longer than the specified 0
Created a chunk of size 405, which is longer than the specified 0
Created a chunk of size 523, which is longer than the specified 0
Created a chunk of size 793, which is longer than the specified 0
Created a chunk of size 165, which is longer than the specified 0
Created a chunk of size 389, which is longer than the specified 0
Created a chunk of size 254, which is longer than the specified 0
Created a chunk of size 1422, which is longer than the specified 0
Created a chunk of size 1083, which is longer than the specified 0
Created a chunk of size 1144, which is longer than the specified 0
Created a chunk of size 1268, which is longer than the specified 0
Created a chunk of size 790, which is longer than the specified 0
Created a chunk of size 297, which is longer than the specified 0
Created a chunk of size 1086, which is longer than the specified 0
Created a chunk of size 874, which is longer than the specified 0
Created a chunk of size 256, which is longer than the specified 0
Created a chunk of size 876, which is longer than the specified 0
Created a chunk of size 806, which is longer than the specified 0
Created a chunk of size 1812, which is longer than the specified 0
Created a chunk of size 1830, which is longer than the specified 0
Created a chunk of size 1064, which is longer than the specified 0
Created a chunk of size 955, which is longer than the specified 0
Created a chunk of size 1180, which is longer than the specified 0
Created a chunk of size 281, which is longer than the specified 0
Created a chunk of size 281, which is longer than the specified 0
Created a chunk of size 286, which is longer than the specified 0
Created a chunk of size 1284, which is longer than the specified 0
Created a chunk of size 1642, which is longer than the specified 0
Created a chunk of size 757, which is longer than the specified 0
Created a chunk of size 1930, which is longer than the specified 0
Created a chunk of size 872, which is longer than the specified 0
Created a chunk of size 2008, which is longer than the specified 0
Created a chunk of size 2285, which is longer than the specified 0
Created a chunk of size 173, which is longer than the specified 0
Created a chunk of size 1003, which is longer than the specified 0
Created a chunk of size 577, which is longer than the specified 0
Created a chunk of size 288, which is longer than the specified 0
Created a chunk of size 255, which is longer than the specified 0
Created a chunk of size 1142, which is longer than the specified 0
Created a chunk of size 557, which is longer than the specified 0
Created a chunk of size 1143, which is longer than the specified 0
Created a chunk of size 243, which is longer than the specified 0
Created a chunk of size 1086, which is longer than the specified 0
Created a chunk of size 1483, which is longer than the specified 0
Created a chunk of size 221, which is longer than the specified 0
Created a chunk of size 1135, which is longer than the specified 0
Created a chunk of size 722, which is longer than the specified 0
Created a chunk of size 668, which is longer than the specified 0
Created a chunk of size 765, which is longer than the specified 0
Created a chunk of size 606, which is longer than the specified 0
Created a chunk of size 570, which is longer than the specified 0
Created a chunk of size 965, which is longer than the specified 0
Created a chunk of size 857, which is longer than the specified 0
Created a chunk of size 1032, which is longer than the specified 0
Created a chunk of size 189, which is longer than the specified 0
Created a chunk of size 367, which is longer than the specified 0
Created a chunk of size 495, which is longer than the specified 0
Created a chunk of size 652, which is longer than the specified 0
Created a chunk of size 348, which is longer than the specified 0
Created a chunk of size 733, which is longer than the specified 0
Created a chunk of size 525, which is longer than the specified 0
Created a chunk of size 1015, which is longer than the specified 0
Created a chunk of size 970, which is longer than the specified 0
Created a chunk of size 204, which is longer than the specified 0
Created a chunk of size 688, which is longer than the specified 0
Created a chunk of size 544, which is longer than the specified 0
Created a chunk of size 242, which is longer than the specified 0
Created a chunk of size 207, which is longer than the specified 0
Created a chunk of size 376, which is longer than the specified 0
Created a chunk of size 931, which is longer than the specified 0
Created a chunk of size 564, which is longer than the specified 0
Created a chunk of size 854, which is longer than the specified 0
Created a chunk of size 715, which is longer than the specified 0
Created a chunk of size 749, which is longer than the specified 0
Created a chunk of size 712, which is longer than the specified 0
Created a chunk of size 324, which is longer than the specified 0
Created a chunk of size 241, which is longer than the specified 0
Created a chunk of size 1088, which is longer than the specified 0
Created a chunk of size 723, which is longer than the specified 0
Created a chunk of size 245, which is longer than the specified 0
Created a chunk of size 227, which is longer than the specified 0
Created a chunk of size 704, which is longer than the specified 0
Created a chunk of size 1912, which is longer than the specified 0
Created a chunk of size 395, which is longer than the specified 0
Created a chunk of size 485, which is longer than the specified 0
Created a chunk of size 622, which is longer than the specified 0
Created a chunk of size 559, which is longer than the specified 0
Created a chunk of size 556, which is longer than the specified 0
Created a chunk of size 386, which is longer than the specified 0
Created a chunk of size 229, which is longer than the specified 0
Created a chunk of size 425, which is longer than the specified 0
Created a chunk of size 418, which is longer than the specified 0
Created a chunk of size 284, which is longer than the specified 0
Created a chunk of size 166, which is longer than the specified 0
Created a chunk of size 624, which is longer than the specified 0
Created a chunk of size 2616, which is longer than the specified 0
Created a chunk of size 1580, which is longer than the specified 0
Created a chunk of size 389, which is longer than the specified 0
Created a chunk of size 994, which is longer than the specified 0
Created a chunk of size 847, which is longer than the specified 0
Created a chunk of size 263, which is longer than the specified 0
Created a chunk of size 336, which is longer than the specified 0
Created a chunk of size 1530, which is longer than the specified 0
Created a chunk of size 213, which is longer than the specified 0
Created a chunk of size 291, which is longer than the specified 0
Created a chunk of size 2030, which is longer than the specified 0
Created a chunk of size 396, which is longer than the specified 0
Created a chunk of size 1619, which is longer than the specified 0
Created a chunk of size 698, which is longer than the specified 0
Created a chunk of size 822, which is longer than the specified 0
Created a chunk of size 354, which is longer than the specified 0
Created a chunk of size 843, which is longer than the specified 0
Created a chunk of size 1189, which is longer than the specified 0
Created a chunk of size 195, which is longer than the specified 0
Created a chunk of size 508, which is longer than the specified 0
Created a chunk of size 663, which is longer than the specified 0
Created a chunk of size 1282, which is longer than the specified 0
Created a chunk of size 260, which is longer than the specified 0
Created a chunk of size 242, which is longer than the specified 0
Created a chunk of size 215, which is longer than the specified 0
Created a chunk of size 198, which is longer than the specified 0
Created a chunk of size 1268, which is longer than the specified 0
Created a chunk of size 1277, which is longer than the specified 0
Created a chunk of size 198, which is longer than the specified 0
Created a chunk of size 1056, which is longer than the specified 0
Created a chunk of size 378, which is longer than the specified 0
Created a chunk of size 269, which is longer than the specified 0
Created a chunk of size 177, which is longer than the specified 0
Created a chunk of size 225, which is longer than the specified 0
Created a chunk of size 222, which is longer than the specified 0
Created a chunk of size 784, which is longer than the specified 0
Created a chunk of size 969, which is longer than the specified 0
Created a chunk of size 613, which is longer than the specified 0
Created a chunk of size 163, which is longer than the specified 0
Created a chunk of size 757, which is longer than the specified 0
Created a chunk of size 289, which is longer than the specified 0
Created a chunk of size 245, which is longer than the specified 0
Created a chunk of size 963, which is longer than the specified 0
Created a chunk of size 232, which is longer than the specified 0
Created a chunk of size 843, which is longer than the specified 0
Created a chunk of size 786, which is longer than the specified 0
Created a chunk of size 648, which is longer than the specified 0
Created a chunk of size 984, which is longer than the specified 0
Created a chunk of size 799, which is longer than the specified 0
Created a chunk of size 193, which is longer than the specified 0
Created a chunk of size 1163, which is longer than the specified 0
Created a chunk of size 253, which is longer than the specified 0
Created a chunk of size 203, which is longer than the specified 0
Created a chunk of size 1058, which is longer than the specified 0

In [9]:
documents[0]

Document(metadata={'source': 'tagged_description.txt'}, page_content='9780002005883 A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.')

In [10]:
db_books = Chroma.from_documents(
        documents,
        embedding=OpenAIEmbeddings())

In [11]:
query = "A book to teach children about nature"
docs = db_books.similarity_search(query, k= 10)
docs

[Document(id='d539d15a-d11b-4a0f-b5f4-f171be015b6b', metadata={'source': 'tagged_description.txt'}, page_content='9780786808069 Children will discover the exciting world of their own backyard in this introduction to familiar animals from cats and dogs to bugs and frogs. The combination of photographs, illustrations, and fun facts make this an accessible and delightful learning experience.'),
 Document(id='45412348-1a8e-4b7c-8017-f2c819775e96', metadata={'source': 'tagged_description.txt'}, page_content="9780786808380 Introduce your babies to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing the baby to some basic -- and sometimes playful -- information about the subjects."),
 Document(id='483079a6-7e6b-4a13-b3dc-9292360686f4', metadata={'source': 'tagged_description.txt'}, page_content="9780786808397 Introduce your baby to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to exopse little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information about the subjects."),
 Document(id='8531493f-4aa8-45e5-b55a-3e28320aa0c2', metadata={'source': 'tagged_description.txt'}, page_content="9780786808373 Introducing your baby to birds, cats, dogs, and babies through fine art, illsutration and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information on the subjects."),
 Document(id='bab09baa-7ed9-4ab0-b4d6-80d1806f5b1b', metadata={'source': 'tagged_description.txt'}, page_content="9780689861130 Children will love joining in and imitating the animal noises and sounds in this big, bold board book format, illustrated with Sandra Boynton's seriously silly signature animals."),
 Document(id='fbee1085-deb5-40a7-97fa-262ae7c10abf', metadata={'source': 'tagged_description.txt'}, page_content='9780789458209 Photographs and text explore the anatomy and life cycle of trees, examining the different kinds of bark, seeds, and leaves, the commercial processing of trees to make lumber, the creatures that live in trees, and other aspects.'),
 Document(id='92af578c-c996-4e29-80ba-fd4ce7ef9c3f', metadata={'source': 'tagged_description.txt'}, page_content='9780786808717 A very special puddle sets Violet the mouse off on her latest nature discovery. It is through this puddle that Violet observes the effect rain has on the world around her. A Mylar puddle on the last page offers children a chance to see their reflection in a puddle, just like Violet!'),
 Document(id='f5973cd7-ae64-4667-bf33-279d686e858c', metadata={'source': 'tagged_description.txt'}, page_content='9780786812912 In her first illustrated book for children, the Pulitzer Prize–winning author Toni Morrison introduces three feisty children who show grown-ups what it really means to be a kid.'),
 Document(id='e2e31580-51b5-4185-b76c-f7b527490fa7', metadata={'source': 'tagged_description.txt'}, page_content='"9780067575208 First published more than three decades ago, this reissue of Rachel Carson\'s award-winning classic brings her unique vision to a new generation of readers. Stunning new photographs by Nick Kelsh beautifully complement Carson\'s intimate account of adventures with her young nephew, Roger, as they enjoy walks along the rocky coast of Maine and through dense forests and open fields, observing wildlife, strange plants, moonlight and storm clouds, and listening to the ""living music"" of insects in the underbrush. ""If a child is to keep alive his inborn sense of wonder."" Writes Carson, ""he needs the companionship of at least one adult who can share it, rediscovering with him the joy, excitement and mystery of the world we live in."" The Sense of Wonder is a refreshing antidote to indifference and a guide to capturing the simple power of discovery that Carson views as essential to life. In her insightful new introduction, Linda Lear remembers Rachel Carson\'s groundbreaking achievements in the context of the legendary environmentalist\'s personal commitment to introducing young and old to the miracles of nature. Kelsh\'s lush photographs inspire sensual, tactile reactions: masses of leaves floating in a puddle are just waiting to be scooped up and examined more closely. An image of a narrow path through the trees evokes the earthy scent of the woods after a summer rain. Close-ups of mosses and miniature lichen fantasy-lands will spark innocent\'as well as more jaded\'imaginations. Like a curious child studying things underfoot and within reach, Kelsh\'s camera is drawn to patterns in nature that too often elude hurried adults\'a stand of beech trees in the springtime, patches of melting snow and the ripples from a pebble tossed into a slow-moving stream. The Sense of Wonder is a timeless volume that will be passed on from children to grandchildren, as treasured as the memory of an early-morning walk when the song of a whippoorwill was heard as if for the first time."'),
 Document(id='b9c9d9c6-462c-4ac3-964b-5da8e1b873dd', metadata={'source': 'tagged_description.txt'}, page_content='9780763620875 When Judy Moody gets serious about protecting the environment, her little brother Stink thinks she is overdoing it, but she manages to inspire her third grade class to undertake an award-winning, environment-saving project. Reprint.')]

In [12]:
# the returned value is book description but what we want to return
# title, authors
books[books["isbn13"] == int(docs[0].page_content.split()[0].strip())]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,titles_and_subtitles,tagged_description
3747,9780786808069,0786808063,Baby Einstein: Neighborhood Animals,Marilyn Singer;Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=X9a4P...,Children will discover the exciting world of t...,2001.0,3.89,16.0,180.0,Baby Einstein: Neighborhood Animals,9780786808069 Children will discover the excit...

In [15]:
def retrieve_semantic_recommendation(
        query: str,
        top_k: int = 10,
) -> pd.DataFrame:
    recs = db_books.similarity_search(query, k= top_k)

    books_list = []

    for i in range(0, len(recs)):
        books_list += [int(recs[i].page_content.strip('"').split()[0])]

    return books[books["isbn13"].isin(books_list)].head(top_k)

In [16]:
retrieve_semantic_recommendation("A book to teach children about nature")

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,titles_and_subtitles,tagged_description
442,9780067575208,006757520X,The Sense of Wonder,Rachel Carson,Nature,http://books.google.com/books/content?id=Zee5S...,"First published more than three decades ago, t...",1998.0,4.39,112.0,1160.0,The Sense of Wonder,9780067575208 First published more than three ...
3214,9780689861130,0689861133,"Moo, Baa, la la La!",Sandra Boynton,Animal sounds,http://books.google.com/books/content?id=Gz40A...,Children will love joining in and imitating th...,2004.0,4.20,14.0,28261.0,"Moo, Baa, la la La!",9780689861130 Children will love joining in an...
3581,9780763620875,0763620874,Judy Moody Saves the World!,Megan McDonald,Juvenile Fiction,http://books.google.com/books/content?id=xDIRB...,When Judy Moody gets serious about protecting ...,2004.0,4.03,160.0,5883.0,Judy Moody Saves the World!,9780763620875 When Judy Moody gets serious abo...
3747,9780786808069,0786808063,Baby Einstein: Neighborhood Animals,Marilyn Singer;Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=X9a4P...,Children will discover the exciting world of t...,2001.0,3.89,16.0,180.0,Baby Einstein: Neighborhood Animals,9780786808069 Children will discover the excit...
3748,9780786808373,0786808373,Baby Einstein: Birds,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=0jxHP...,"Introducing your baby to birds, cats, dogs, an...",2002.0,3.78,20.0,9.0,Baby Einstein: Birds,"9780786808373 Introducing your baby to birds, ..."
3749,9780786808380,0786808381,Baby Einstein: Babies,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=jv4NA...,"Introduce your babies to birds, cats, dogs, an...",2002.0,4.03,20.0,29.0,Baby Einstein: Babies,"9780786808380 Introduce your babies to birds, ..."
3750,9780786808397,078680839X,Baby Einstein: Dogs,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=qut8t...,"Introduce your baby to birds, cats, dogs, and ...",2002.0,3.81,20.0,26.0,Baby Einstein: Dogs,"9780786808397 Introduce your baby to birds, ca..."
3751,9780786808717,0786808713,Baby Einstein: What Does Violet See? Raindrops...,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=95IIA...,A very special puddle sets Violet the mouse of...,2002.0,3.25,18.0,16.0,Baby Einstein: What Does Violet See? Raindrops...,9780786808717 A very special puddle sets Viole...
3760,9780786812912,0786812915,The Big Box,Toni Morrison;Slade Morrison,Juvenile Fiction,http://books.google.com/books/content?id=LyYKA...,"In her first illustrated book for children, th...",2002.0,3.95,48.0,375.0,The Big Box,9780786812912 In her first illustrated book fo...
3797,9780789458209,0789458209,Tree,David Burnie,Juvenile Nonfiction,http://books.google.com/books/content?id=Qwsqj...,Photographs and text explore the anatomy and l...,2000.0,4.07,64.0,5.0,Tree,9780789458209 Photographs and text explore the...

In [17]:
books["categories"].value_counts().reset_index()

                    categories  count
0                      Fiction   2111
1             Juvenile Fiction    390
2    Biography & Autobiography    311
3                      History    207
4           Literary Criticism    124
..                         ...    ...
474               Conspiracies      1
475       Brothers and sisters      1
476             Rock musicians      1
477             Community life      1
478    Indic fiction (English)      1

[479 rows x 2 columns]

In [18]:
category_mapping = {
    "Fiction": "Fiction",
    "Juvenile Fiction": "Children's Fiction",
    "Biography & Autobiography":"Nonfiction",
    "History":"Nonfiction",
    "Literary Criticism":"Nonfiction",
    "Philosophy": "Nonfiction",
    "Religion": "Nonfiction",
    "Comics & Graphic Novels": "Fiction",
    "Drama":"Fiction",
    "Juvenile Nonfiction": "Children's Nonfiction",
    "Science": "Nonfiction",
    "Poetry": "Fiction",
}

books["simple_categories"] = books["categories"].map(category_mapping)

In [19]:
books["simple_categories"].value_counts().reset_index()

       simple_categories  count
0                Fiction   2364
1             Nonfiction    932
2     Children's Fiction    390
3  Children's Nonfiction     57

In [20]:
books[~(books["simple_categories"].isna())]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,titles_and_subtitles,tagged_description,simple_categories
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...,Fiction
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine...",Fiction
8,9780006482079,0006482074,Warhost of Vastmark,Janny Wurts,Fiction,http://books.google.com/books/content?id=uOL0f...,"Tricked once more by his wily half-brother, Ly...",1995.0,4.03,522.0,2966.0,Warhost of Vastmark,9780006482079 Tricked once more by his wily ha...,Fiction
30,9780006646006,000664600X,Ocean Star Express,Mark Haddon;Peter Sutton,Juvenile Fiction,http://books.google.com/books/content?id=I2QZA...,Joe and his parents are enjoying a summer holi...,2002.0,3.50,32.0,1.0,Ocean Star Express,9780006646006 Joe and his parents are enjoying...,Children's Fiction
46,9780007121014,0007121016,Taken at the Flood,Agatha Christie,Fiction,http://books.google.com/books/content?id=3gWlx...,A Few Weeks After Marrying An Attractive Young...,2002.0,3.71,352.0,8852.0,Taken at the Flood,9780007121014 A Few Weeks After Marrying An At...,Fiction
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5178,9781933648279,1933648279,Night Has a Thousand Eyes,Cornell Woolrich,Fiction,http://books.google.com/books/content?id=3Gk6s...,"""Cornell Woolrich's novels define the essence ...",2007.0,3.77,344.0,680.0,Night Has a Thousand Eyes,"9781933648279 ""Cornell Woolrich's novels defin...",Fiction
5188,9784770028969,4770028962,Coin Locker Babies,村上龍,Fiction,http://books.google.com/books/content?id=87DJw...,Rescued from the lockers in which they were le...,2002.0,3.75,393.0,5560.0,Coin Locker Babies,9784770028969 Rescued from the lockers in whic...,Fiction
5189,9788122200850,8122200850,"Cry, the Peacock",Anita Desai,Fiction,http://books.google.com/books/content?id=_QKwV...,This book is the story of a young girl obsesse...,1980.0,3.22,218.0,134.0,"Cry, the Peacock",9788122200850 This book is the story of a youn...,Fiction
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...,Nonfiction
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...,Nonfiction

In [21]:
import torch

print(torch.__version__)

2.6.0

In [22]:
import tensorflow as tf

print(tf.__version__)

2.19.0

In [23]:
from transformers import pipeline

fiction_categories = ["Fiction", "Nonfiction"]

pipe = pipeline("zero-shot-classification",
                model="facebook/bart-large-mnli",
                framework="pt",
                device='mps:0')

Device set to use mps:0

In [24]:
sequence = books.loc[books["simple_categories"] == "Fiction", "description"].reset_index(drop=True)[0]

In [25]:
pipe(sequence, fiction_categories)

{'sequence': 'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.',
 'labels': ['Fiction', 'Nonfiction'],
 'scores': [0.8438265323638916, 0.156173437833786]}

In [26]:
import torch
if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    x = torch.ones(1, device=mps_device)
    print (x)
else:
    print ("MPS device not found.")

tensor([1.], device='mps:0')

In [27]:
import numpy as np

max_index = np.argmax(pipe(sequence, fiction_categories)["scores"])
max_label = pipe(sequence, fiction_categories)["labels"][max_index]
max_label

'Fiction'

In [28]:
def generate_predictions(sequence: str, categories:list) -> str:
    predictions = pipe(sequence, categories)
    max_index = np.argmax(predictions["scores"])
    max_label = predictions["labels"][max_index]
    return max_label

In [29]:
from tqdm import tqdm

actual_cats = []
predicted_cats = []

for i in tqdm(range(0, 300)):
    sequence = books.loc[books["simple_categories"] == "Fiction", "description"].reset_index(drop=True)[i]
    actual_cats += [generate_predictions(sequence, fiction_categories)]
    predicted_cats += ["Fiction"]

100%|██████████| 300/300 [08:30<00:00,  1.70s/it]

In [30]:
for i in tqdm(range(0, 300)):
    sequence = books.loc[books["simple_categories"] == "Nonfiction", "description"].reset_index(drop=True)[i]
    actual_cats += [generate_predictions(sequence, fiction_categories)]
    predicted_cats += ["Nonfiction"]

100%|██████████| 300/300 [20:29<00:00,  4.10s/it]

In [31]:
predictions_df = pd.DataFrame({"actual_category": actual_cats, "predicted_category": predicted_cats})

In [32]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,titles_and_subtitles,tagged_description,simple_categories
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...,Fiction
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,NaN
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine...",Fiction
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...,NaN
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,Mistaken Identity,9788172235222 On A Train Journey Home To North...,NaN
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,Journey to the East,9788173031014 This book tells the tale of a ma...,NaN
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...,NaN
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...,Nonfiction
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...,Nonfiction

In [33]:
predictions_df["correct_prediction"] = (
    np.where(predictions_df["actual_category"] == predictions_df["predicted_category"], 1, 0)
)

In [35]:
accuracy = predictions_df["correct_prediction"].sum()/ len(predictions_df)
accuracy

0.7783333333333333

In [37]:
isbn13 = []
predicted_cats = []

missing_cats = books.loc[books["simple_categories"].isna(), ["isbn13", "description"]].reset_index(drop=True)
missing_cats

             isbn13                                        description
0     9780002261982  A new 'Christie for Christmas' -- a full-lengt...
1     9780006280897  Lewis' work on the nature of love divides love...
2     9780006280934  "In The Problem of Pain, C.S. Lewis, one of th...
3     9780006380832  Until Vasco da Gama discovered the sea-route t...
4     9780006470229  A new-cover reissue of the fourth book in the ...
...             ...                                                ...
1449  9788125026600  Not only does Nietzsche for Beginners delve in...
1450  9788171565641  Forster's lively, informed originality and wit...
1451  9788172235222  On A Train Journey Home To North India After L...
1452  9788173031014  This book tells the tale of a man who goes on ...
1453  9788179921623  Wisdom to Create a Life of Passion, Purpose, a...

[1454 rows x 2 columns]

In [38]:
for i in tqdm(range(0, len(missing_cats))):
    sequence = missing_cats["description"][i]
    predicted_cats += [generate_predictions(sequence, fiction_categories)]
    isbn13 += [missing_cats["isbn13"][i]]

100%|██████████| 1454/1454 [1:14:45<00:00,  3.08s/it]

In [39]:
missing_predictions_df = pd.DataFrame({"isbn13": isbn13, "predicted_category": predicted_cats})
missing_predictions_df

             isbn13 predicted_category
0     9780002261982            Fiction
1     9780006280897         Nonfiction
2     9780006280934         Nonfiction
3     9780006380832         Nonfiction
4     9780006470229            Fiction
...             ...                ...
1449  9788125026600         Nonfiction
1450  9788171565641            Fiction
1451  9788172235222            Fiction
1452  9788173031014         Nonfiction
1453  9788179921623            Fiction

[1454 rows x 2 columns]

In [40]:
books = pd.merge(books, missing_predictions_df, on="isbn13", how="left")
books["simple_categories"] = np.where(books["simple_categories"].isna(), books["predicted_category"], books["simple_categories"])
books = books.drop(columns = ["predicted_category"])

In [41]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,titles_and_subtitles,tagged_description,simple_categories
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...,Fiction
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,Fiction
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine...",Fiction
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...,Nonfiction
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le...",Nonfiction
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,Mistaken Identity,9788172235222 On A Train Journey Home To North...,Fiction
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,Journey to the East,9788173031014 This book tells the tale of a ma...,Nonfiction
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...,Fiction
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...,Nonfiction
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...,Nonfiction

In [42]:
books.to_csv("books_with_categories.csv", index=False)